# Generated by Django 5.2 on 2025-05-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetectionResult',
            new_name='Detections',
        ),
    ]
